### ISSUE TITLE
[Bug]: Multiple emails received with subject line 'APIsec bot for APIsec Scan Summary Report ...'

### ISSUE THREAD

**Issue by atef-aa** [apisec-inc/Support#104] opened 2022-07-20 22:34 UTC
### Severity

Medium

### What happened?

Earlier this week I created a project called Demoaa.  Then, under Integrations > created a Report Storage.  I have received several emails today (Wednesday) with the same subject, content and attachment.  I don't recall running the Scan on the frontend or triggering any command.

The email subject for these 11 emails was the same:
APIsec Scan Summary Report - Demoaa - Master - **1**

After few hours I received another exact email but just one time.  This time the subject is:
APIsec Scan Summary Report - Demoaa - Master - **2**

Attached the emails and the actual PDF:
**Email**
[APIsec Mail - APIsec Scan Summary Report - Demoaa - Master - 1.pdf](https://github.com/apisec-inc/Support/files/9154861/APIsec.Mail.-.APIsec.Scan.Summary.Report.-.Demoaa.-.Master.-.1.pdf)

**The report results are different.**. 
I compared some reports and the results are different. Attached the first and and the 11th pdf for reference.
[first-attachment-APIsec_scan_summary_report_NetBanking_Demoaa_07202022.pdf](https://github.com/apisec-inc/Support/files/9154857/first-attachment-APIsec_scan_summary_report_NetBanking_Demoaa_07202022.pdf)
[eleventh-attachment-APIsec_scan_summary_report_NetBanking_Demoaa_07202022 (1).pdf](https://github.com/apisec-inc/Support/files/9154856/eleventh-attachment-APIsec_scan_summary_report_NetBanking_Demoaa_07202022.1.pdf)

Please let me know if there are any questions.

**Comment by muqeetkhan20** [comment] 2022-07-21 06:18
@atef-aa first of it's strange to get the emails without triggering any report.
second thing, report storage kicks only pen test, developer and compliance reports. We doesn't have code in place to store the summary reports.
however, we tried triggering the summary reports, and unable to reproduce the issue (i.e. repeated emails), just we got one email.
Please give it a try again and let's see how it goes.

**Comment by muqeetkhan20** [comment] 2022-08-04 05:40
@atef-aa I am closing this ticket.

**Closed by muqeetkhan20** 2022-08-04 05:40 UTC
Labels: bug
