### ISSUE TITLE
[Bug]: Playbook Generation Failing due to Payload size

### ISSUE THREAD

**Issue by fersy02** [apisec-inc/Support#84] opened 2022-06-06 06:48 UTC
### Severity

Blocker

### What happened?

Previously playbook generation into multiple categories used to fail with a proper error message. Now, the playbook generation task is failing due to a timeout error and impacting the performance of the control plane.

Expected Response
![image](https://user-images.githubusercontent.com/47815523/172109908-458ea417-39cc-40f0-bca6-9e29e1e1b609.png)

Actual Response:
![image](https://user-images.githubusercontent.com/47815523/172109956-3cd94abf-cd71-4130-b2ee-a5bac55747c3.png)

**Comment by fersy02** [comment] 2022-06-07 16:53
@Mohammed-Luqman-Shareef @Abdullah-Akbar @intesar 
Any updates on this ticket? Currently, we are blocked on a couple of POVs, and it is also preventing us from generating playbooks in other projects when resources are overwhelmed due to this issue. 

Due to privacy reasons, the OAS is not attached to this ticket. Please reach out to @Mohammed-Luqman-Shareef or @Abdullah-Akbar for more details.

**Comment by intesar** [comment] 2022-06-08 18:17
@fersy02 have your team comment on a few (10,50, 100, etc.) endpoints and try to onboard the API.
@Mohammed-Luqman-Shareef Did we find the root cause of the problem?

**Comment by muqeetkhan20** [comment] 2022-06-15 09:11
@Mohammed-Luqman-Shareef skipAbac is in place now, do we have any more iterations or can we close this ticket?

**Comment by Mohammed-Luqman-Shareef** [comment] 2022-06-15 13:51
> @Mohammed-Luqman-Shareef skipAbac is in place now, do we have any more iterations or can we close this ticket?

The skipAbac flag will be added on the Details page.

**Comment by Mohammed-Luqman-Shareef** [comment] 2022-06-16 06:59
@muqeetkhan20 as discussed you can close the ticket.

**Closed** 2022-06-16 07:08 UTC
Labels: bug, blocker, playbook, QA

**Comment by muqeetkhan20** [comment] 2022-07-14 06:03
@wesleymeier the large payload spec will not allow you to generate playbooks for all the categories. It only allows you to generate unsecured, rest you have to manually create a single category at a time through playbook management.

I tried with the big file and i was able to generate the unsecured with the below notification message in the activities.
![image](https://user-images.githubusercontent.com/68276700/178911315-b60d7500-2933-45d0-a7cf-daae8cbd36a6.png)

if possible, please provide us with your spec.
