### ISSUE TITLE
[Bug]: Error displayed upon reloading an OAS via URL

### ISSUE THREAD

**Issue by fersy02** [apisec-inc/Support#97] opened 2022-06-30 05:28 UTC
### Severity

Medium

### What happened?

**We support registering a private OAS URL after whitelisting the control plane IP (cloud.fxlabs.io)**

One of our customers has reported that they couldn't reload a private OpenAPI specification URL.
I have downloaded the file using a playbook and registered it successfully. Upon reloading the specification URL, it throws the following error:
![image](https://user-images.githubusercontent.com/47815523/176598116-2edefa3b-6d35-4bd2-8fa8-6d055d734d91.png)

Logs are not available for debugging this issue:
![image](https://user-images.githubusercontent.com/47815523/176598196-cfe873fc-f6ac-48a9-b79d-fd8a07758215.png)

![image](https://user-images.githubusercontent.com/47815523/176598348-c359a8e3-f0f4-451d-90dd-8ad2b3621949.png)

Since the URL is not publicly accessible, we have requested the client to whitelist the Control Plane IP: 163.107.196.104

Details shared with @Mohammed-Luqman-Shareef to reproduce this issue.

**Comment by muqeetkhan20** [comment] 2022-06-30 05:42
Unable to reproduce this error in NetBanking project - fyi

**Comment by Mohammed-Luqman-Shareef** [comment] 2022-06-30 05:45
Waiting for the IP address to be whitelisted.
@fersy02 Pls let us know once it is done.

**Comment by fersy02** [comment] 2022-07-04 04:07
@Mohammed-Luqman-Shareef 
The client has double-checked and confirmed that the IP is whitelisted. Do we have to whitelist any additional IPs apart from this: 163.107.196.104
We also need better error handling. In this case, neither the client nor us could debug this issue as the logs are empty.

**Comment by Mohammed-Luqman-Shareef** [comment] 2022-07-04 06:02
@fersy02 The OAS url you provided in the email is not accessible from this machine.   Is the url open or does it require any credentials to access?

**Comment by sarasheed** [comment] 2022-07-04 06:21
This is our production's VM IP 104.196.107.163.

**Comment by Mohammed-Luqman-Shareef** [comment] 2022-07-20 03:43
Closing this ticket as the resolution is provided and no further action pending.

**Closed by Mohammed-Luqman-Shareef** 2022-07-20 03:43 UTC
Labels: bug, playbook
