### ISSUE TITLE
[Bug]: Cannot reload OAS via URL behind a Firewall

### ISSUE THREAD

**Issue by fersy02** [apisec-inc/Support#148] opened 2022-09-09 12:29 UTC
### Severity

Medium

### What happened?

One of our clients has reported that they cannot reload spec since the prod migration and getting an error: 
![image](https://user-images.githubusercontent.com/47815523/189349173-ed6ee528-2689-4e83-85b4-43a17f702d49.png)

I have ensured the client has whitelisted the prod cluster IP: 104.196.107.163

Whitelisting of the Prod IP worked well until we migrated to Kubernetes. Please let us know if any additional IPs should be whitelisted. I have shared the details with @Mohammed-Luqman-Shareef. 

Please let me know if any additional details are needed.

**Comment by SyedsImran** [comment] 2022-09-09 19:05
I was able to reproduce the error, see below screenshot for reference.
In below screenshot case, I have disabled port 8080 of Netbanking app and tried to reload the spec.

I think in the client case either they application is down or ports 80,443 are not exposed.

![image](https://user-images.githubusercontent.com/100760767/189424993-0ad8f32e-5545-4f04-b9b5-52c80eea5b75.png)

**Comment by fersy02** [comment] 2022-09-12 17:17
@SyedsImran, Thanks for looking into this issue. 

I have checked the configurations, and I could see port 443 is exposed and the URL is working. 
The URL works fine when I use a playbook to execute it with an on-premises scanner.

The error is the same, but the issue is not with the availability or 443 not exposed.

**Comment by fersy02** [comment] 2022-09-13 13:07
@Mohammed-Luqman-Shareef @atef-aa 
Appreciate any updates on this issue as the client is chasing us for a fix. Please remember the reload spec worked before migrating to Kubernetes.

**Comment by atef-aa** [comment] 2022-09-14 03:06
@SyedsImran please look what's causing this and expedite.

**Comment by Afra-APIsec** [comment] 2022-09-14 13:11
@SyedsImran, Issue still exists, but now receiving the error message, "Transaction silently rolled back".

**Comment by SyedsImran** [comment] 2022-09-14 16:24
@Afra-APIsec How's that error message impacting us?
Are playbooks not regenerating at all or some are regenerating while others throw are not.
what's happening?

**Comment by Afra-APIsec** [comment] 2022-09-14 16:44
@SyedsImran the spec reload functionality is not working.
hence, the playbooks are not getting regenerated.

**Comment by Abdullah-Akbar** [comment] 2022-09-16 14:12
I just tried this , not getting any error but playbook generation is not working due to vc-git env issues, i think.

**Comment by SyedsImran** [comment] 2022-09-18 07:45
Last Evening around 10PM IST all prod cluster Pods and VMs got restarted for some odd reason. We are investigating it.
Everything is working fine, but as a result of the above cluster VMs public IPs got changed which were dynamic IPs(two of the three).

@apisec-inc/devops  have turned dynamic IPs into static IPs now. Below are the new  static IPs.
34.75.76.48 (Changed IP)
34.75.241.98 (Unchanged IP)
35.185.110.56 (Changed IP)
@apisec-inc/support  or @fersy02   team will have to whitelist these IPs once with clients.

![image](https://user-images.githubusercontent.com/100760767/190891173-daa088fc-8ac0-4dcf-88c2-fac60a7fc380.png)

**Comment by mjameel757** [comment] 2022-09-19 08:44
@apisec-inc/devops @apisec-inc/engineering @intesar 

Assigning static IP's to node is not a best practice not it's a recommended solution when we go with k8s as a cloud managed services

GKE Handles autoscaling scenarios by using features like 
1. HPA for adding removing Pods based on utilization metrics
2. Cluster Autoscaler, for adding and removing Nodes based on scheduled workload
3. Node auto-provisioning for dynamically crating new node pools that match the needs of user pods.

Based on all this scenarios when cluster spins a new node or recreate a node it will come with a new External IP which is Ephemeral 
converting the Ephemeral IP to static IP will not solve the issue rather it cost us more on Billing

I wont think spec reload issue is concerned with Node IP's we need to investigate this with @apisec-inc/engineering

**Comment by intesar** [comment] 2022-10-10 17:48
@mjameel757, what is the solution to make sure the IPs are predictable? Is there a way to assign an IP pool to the nodes?

**Comment by mjameel757** [comment] 2022-10-13 05:19
comming week end we are going to implement IP masquerade agent on cluster..

**Comment by atef-aa** [comment] 2022-11-03 13:42
@mjameel757 - did this implementation solve this problem?

**Comment by SyedsImran** [comment] 2022-12-21 10:33
Implemented ip-masquerading feature on prod k8s cluster. 
With this implementation all the outbound requests from the deployed pods running across all the k8s cluster nodes, will go through single cloudNat reserved public IP. 

Now clients needs to add below IPs for inbound and outbound requests in their firewall settings.

Client Firewall Inbound: 34.23.155.76 
This is for apisec control-plane pod to connect with the client application, running on a specific port like 8080, sitting behind a firewall.

Client Firewall Outbound: 104.196.107.163
This is for clients to connect with apisec product through UI(https://cloud.apisec.ai/) on ports 80 & 443 and  port 5671 for privately deployed scanners on customer environments, to connect apisec product(rabbitmq-queues).

**Comment by GhouseApisec** [comment] 2023-01-03 07:49
@fersy02, Can you pls check with client and confirm whether able to reload the OAS URL behind the Firewall after IP Masquerading.  If yes we can close this ticket.

**Comment by fersy02** [comment] 2023-01-04 07:14
@GhouseApisec - We have notified all our customers and waiting for their feedback. The teams are returning from their vacation, and we should expect feedback by early next week. I will let you know of any updates for the same.

**Comment by fersy02** [comment] 2023-01-11 16:07
@GhouseApisec 
We got the confirmation from the client today, and it is working as expected. This can be closed.

**Closed** 2023-01-11 16:26 UTC
Labels: bug
