### ISSUE TITLE
[Report]: Newly Added endpoints fail to show in the Reports Tab and Spec comparision report is empty

### ISSUE THREAD

**Issue by fersy02** [apisec-inc/Support#197] opened 2022-10-26 12:54 UTC
### Severity

Bug

### What happened?

One of our clients has recently reloaded their OAS, and the number of endpoints has increased by 19. Although the total number of endpoints has changed, the reports tab still shows the previous count, and the spec comparison report has no data.

Here are the details:

Screenshot of the project dashboard before reloading the OAS:
![image](https://user-images.githubusercontent.com/47815523/198030764-51909633-7684-4a52-b106-bd6f87f2f6e9.png)

Screenshot of the project dashboard after reloading the OAS:
![image](https://user-images.githubusercontent.com/47815523/198030318-44ba2121-ef30-4de7-ac9f-4a11328fe97e.png)

The reports tab still shows the previous count:
![image](https://user-images.githubusercontent.com/47815523/198030528-720dcecd-a8b1-4dec-9a73-d4b2ced66e0e.png)

The Spec Comparision report has no data:
![image](https://user-images.githubusercontent.com/47815523/198030660-534be9f9-edaf-4c5b-aab1-bb73300588de.png)

**Comment by YasmeenFatima** [comment] 2022-10-27 06:45
This issue is not reproducible to me, i cross verified with Net banking spec
Reports tab:
![image](https://user-images.githubusercontent.com/69448810/198210450-7495d5a3-97a6-4dc4-936d-08fcf0cb3878.png)
Spec Comparision report:
![image](https://user-images.githubusercontent.com/69448810/198210479-3126290a-99bf-4216-beb6-1687feb91fa1.png)
Dashboard:
![image](https://user-images.githubusercontent.com/69448810/198210512-4b8477aa-9cd2-43aa-85d5-939da3fcbe80.png)

**Comment by YasmeenFatima** [comment] 2022-11-02 10:09
Checked with supplied spec, the issue is reproducible. It's client specific.

**Comment by atef-aa** [comment] 2022-11-03 05:09
@zafar0506 or @muqeetkhan20 - One of you please pick this item.

**Comment by zafar0506** [comment] 2022-11-03 05:29
@atef-aa : I will look into it and update the ticket accordingly.

**Comment by zafar0506** [comment] 2022-11-12 20:58
@fersy02  : Upon investigation,  it has been observed that the newly loaded spec file has relative schema paths and thus causing the issue. Could you please get the updated spec file from the customer with  inline schema references so that we can re-test and close the issue.

**Comment by fersy02** [comment] 2022-11-16 03:52
@zafar0506 - I believe the issue might fix when we reload the spec without relative paths in the schema. Still, the functionality comparison is with a new project registration that works fine. As discussed, let's ensure the functionality is consistent, be it new project registration or reloading this spec in an existing project. Please let me know if you need any additional clarifications.

**Comment by mmuqtaar** [comment] 2022-12-16 11:31
@fersy02 I'm not able reproduce the issue. Let's close the ticket

**Comment by fersy02** [comment] 2022-12-16 11:44
@mmuqtaar - QA was able to reproduce this issue with the given spec. Please ask them to reverify with the same spec before closing this ticket.

**Comment by YasmeenFatima** [comment] 2022-12-21 06:47
@mmuqtaar - This issue is reproducible from the supplied spec.

**Comment by YasmeenFatima** [comment] 2023-01-02 07:04
Verified in dev
![image](https://user-images.githubusercontent.com/69448810/210202399-014695e5-c46b-4bbc-879c-a4b47544407f.png)
![image](https://user-images.githubusercontent.com/69448810/210202472-ac634ae3-026c-4f7d-9598-1230c11c22c4.png)
![image](https://user-images.githubusercontent.com/69448810/210202417-00b33a39-a250-4430-85c9-5bfd12a34d4c.png)

**Closed** 2023-01-02 07:09 UTC
Labels: bug, QE
